[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
serde = "1.0"
toml = "0.8.19"
glob = "0.3.2"
chrono = "0.4.39"

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["tera"]
